services:
  - type: web
    name: ipsc-tracker
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.address 0.0.0.0 --server.port $PORT
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATA_ROOT
        value: /var/data
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 2
